config/routes.rb
TradeServer::Application.routes.draw do
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :trades

  match 'trades/pair/:pair' => 'trades#pair'
  match 'trades/:start_date/:end_date' => 'trades#range'
  

end

app/models/trade.rb
class Trade
  include Mongoid::Document
  store_in collection: "test_trades"
  field :rss_guid, type: String
  field :dtcc_id, type: String
  field :orig_dtcc_id, type: String
  field :title, type: String
  field :pub_date, type: Hash
  field :asset, type: String
  field :taxonomy, type: String
  field :time_stamp, type: Hash
  field :status, type: Trade
  field :und, type: String
  field :acc, type: String
  field :und_not, type: Numeric 
  field :acc_not, type: Numeric 
  field :expiry, type: Hash 
  field :strike, type: Numeric
  field :type, type: String
  field :prem_ccy, type: String
  field :prem, type: Numeric
  field :m_spot_ref, type: Numeric
  field :m_usd_equiv_not, type: Numeric
  
  index( { dtcc_id: 1 } , { unique: true } )
  index( { taxonomy: 1} )
  index( { m_usd_equiv_not: 1} )
  index( { "expiry.d" => -1 } )
  index( { "time_stamp.d" =>  -1 } )

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  field :name
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @trades = Trade.all
  end
end

app/controllers/trades_controller.rb
BIG_NUM = 25000000

class TradesController < ApplicationController
  # GET /trades
  # GET /trades.json
  def index

    @trades = Trade.all.desc(:time_stamp).limit(100)

    # function() { return this.und_not > this.acc_not }

    # @sig_trades = Trade.where(function() { return this.und_not > this.acc_not }).and({:und_not.gte => BIG_NUM}, {:acc_not.gte => BIG_NUM}).desc(:time_stamp).limit(100)
    @sig_trades = Trade.desc(:m_usd_equiv_not).limit(100)
    @opt_trades = Trade.where(:title.ne => "ForeignExchange:NDF").desc(:time_stamp).limit(100)
    @ndf_trades = Trade.where(title: "ForeignExchange:NDF").desc(:time_stamp).limit(100)

    @pairs = Trade.distinct(:m_alpha_pair)
    @pairs_hash = {}
    @pairs.each do |pair|
      @pairs_hash[pair] = Trade.where(m_alpha_pair: pair).sum(:m_usd_equiv_not)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trades }
    end
  end


  # GET /trades/range/start_date/end_date
  # GET /trades/range/start_date/end_date.json
  def range
    start_date = Time.parse(params[:start_date]).utc
    end_date = Time.parse(params[:end_date]).utc

    # @trades = Trade.where( 
    # :time_stamp.gte => start_date,
    # :time_stamp.lte => end_date 
    # ).desc(:time_stamp).limit(100)
    @trades = Trade.between( time_stamp: start_date..end_date).desc(:time_stamp).limit(100)

    puts "Params : #{params[:start_date]}-#{params[:end_date]}"
    puts "parsed : #{start_date}-#{end_date}"
    @opt_trades = Trade.where(:time_stamp => {'$gte' => start_date,'$lt' => end_date}).desc(:time_stamp).limit(100)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trades }
    end
  end


  # GET /trades/1
  # GET /trades/1.json
  def show
    @trade = Trade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trade }
    end
  end

  # GET /trades/new
  # GET /trades/new.json
  def new
    @trade = Trade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trade }
    end
  end

  # GET /trades/1/edit
  def edit
    @trade = Trade.find(params[:id])
  end



  # POST /trades
  # POST /trades.json
  def pair
    und = params[:pair][0..2]
    acc = params[:pair][3..5]
    alpha_pair = und < acc ? und+acc : acc+und 
    puts alpha_pair
    @trades = Trade.where(  m_alpha_pair: alpha_pair, :m_usd_equiv_not.gte => BIG_NUM ).desc(:time_stamp).limit(100)
    puts @trades.count
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trades }
    end
  end




  # POST /trades
  # POST /trades.json
  def create
    @trade = Trade.new(params[:trade])

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully created.' }
        format.json { render json: @trade, status: :created, location: @trade }
      else
        format.html { render action: "new" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trades/1
  # PUT /trades/1.json
  def update
    @trade = Trade.find(params[:id])

    respond_to do |format|
      if @trade.update_attributes(params[:trade])
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade = Trade.find(params[:id])
    @trade.destroy

    respond_to do |format|
      format.html { redirect_to trades_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h3>Home</h3>

<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

<h2> Trade Server </h2>
<p>Trades <%= link_to 'Trades', trades_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TradeServer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <ul class="hmenu">
    <%= render 'shared/navigation' %>
  </ul>
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>
<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
  <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>

app/views/trades/_form.html.erb
<%= form_for(@trade) do |f| %>
  <% if @trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% @trade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<h1>Trade list summary (100 limit)</h1>

<h2>Trade notional summary<h2>
<table id ='trade_table'>
	<thead>
		<tr>
			<th> Pair</th>
			<th>USD Equiv Notional</th>
		</tr>
	</thead>
	<tbody>
		<% @pairs_hash.sort_by{|p,n| n}.reverse.each do |p_array|%>
		<tr>
			<td><%= p_array[0] %></td>
			<td><%= number_with_precision(p_array[1], :precision => 0, :delimiter => ',')%> </td>
		</tr>
		<% end %>
	</tbody>
</table>


<h2> Latest (100/<%=@opt_trades.count%>) options trades </h2>

	<%= date_select "report", "start_date", :default => -1.days.from_now %>
	to <%= date_select "report", "end_date", :default => 0.days.from_now %>
</p>

<table id ='trade_table'>
	<thead>
		<tr>
			<th></th>
			<th></th>
			<th></th>

			<th>DTCC Id</th>
			<th>TimeStamp</th>
			<th>UND</th>
			<th>ACC</th>
			<th>UND Notional</th>
			<th>ACC Notional</th>
			<th>USD Equiv Notional</th>
			<th>Strike</th>
			<th>Sub Type</th>
			<th>Expiry</th>
			<th>PAY</th>
			<th>Prem</th>
			<th>Trade Type</th>
			<th>Spot Ref</th>
		</tr>
	</thead>

	<tbody>
		<% @opt_trades.each do |trade| %>
		<tr>
			<td><%= link_to 'Show', trade %></td>
			<td><%= link_to 'Edit', edit_trade_path(trade) %></td>
			<td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>

			<td><%= trade.dtcc_id  %> </td>
			<% ts = Time.parse(trade.time_stamp["d"]+" "+trade.time_stamp["t"]) if trade.time_stamp %>
			<td><%= ts.strftime( '%Y %b %d %H:%M:%S' ) if trade.time_stamp  %> </td>
			<td><%= trade.und %> </td>
			<td><%= trade.acc %> </td>
			<td><%= number_with_precision(trade.und_not, :precision => 0, :delimiter => ',') %> </td>
			<td><%= number_with_precision(trade.acc_not, :precision => 0, :delimiter => ',')  %> </td>
			<td><%= number_with_precision(trade.m_usd_equiv_not, :precision => 0, :delimiter => ',')  %> </td>
			<td><%= trade.strike %> </td>
			<td><%= trade.type %> </td>
			<% ts = Time.parse(trade.expiry.to_s) if trade.expiry %>
			<td><%= ts.strftime( '%d %b %Y' ) if trade.expiry  %> </td>
			<td><%= trade.prem_ccy %> </td>
			<td><%= number_with_precision(trade.prem, :precision => 0, :delimiter => ',') %> </td>			
			<td><%= trade.taxonomy %> </td>
			<td><%= trade.m_spot_ref %> </td>
		</tr>
		<% end %>
	</tbody>
</table>

<h2> Top 100 large trades </h2>

<table id ='trade_table'>
	<thead>
		<tr>
			<th></th>
			<th></th>
			<th></th>

			<th>DTCC Id</th>
			<th>TimeStamp</th>
			<th>UND</th>
			<th>ACC</th>
			<th>UND Notional</th>
			<th>ACC Notional</th>
			<th>USD Equiv Notional</th>
			<th>Strike</th>
			<th>Sub Type</th>
			<th>Expiry</th>
			<th>PAY</th>
			<th>Prem</th>
			<th>Trade Type</th>
			<th>Spot Ref</th>
		</tr>
	</thead>

	<tbody>
		<% @sig_trades.each do |trade| %>
		<tr>
			<td><%= link_to 'Show', trade %></td>
			<td><%= link_to 'Edit', edit_trade_path(trade) %></td>
			<td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>

			<td><%= trade.dtcc_id  %> </td>
			<% ts = Time.parse(trade.time_stamp.to_s) if trade.time_stamp %>
			<td><%= ts.strftime( '%Y %b %d %H:%M:%S' ) if trade.time_stamp  %> </td>
			<td><%= trade.und %> </td>
			<td><%= trade.acc %> </td>
			<td><%= number_with_precision(trade.und_not, :precision => 0, :delimiter => ',') %> </td>
			<td><%= number_with_precision(trade.acc_not, :precision => 0, :delimiter => ',')  %> </td>
			<td><%= number_with_precision(trade.m_usd_equiv_not, :precision => 0, :delimiter => ',')  %> </td>
			<td><%= trade.strike %> </td>
			<td><%= trade.type %> </td>
			<% ts = Time.parse(trade.expiry.to_s) if trade.expiry %>
			<td><%= ts.strftime( '%d %b %Y' ) if trade.expiry  %> </td>
			<td><%= trade.prem_ccy %> </td>
			<td><%= number_with_precision(trade.prem, :precision => 0, :delimiter => ',') %> </td>			
			<td><%= trade.taxonomy %> </td>
			<td><%= trade.m_spot_ref %> </td>
		</tr>
		<% end %>
	</tbody>
</table>
<br />

<h2> Latest (100 of <%=@trades.count%>) all trades </h2>
<table id ='trade_table'>
	<thead>
		<tr>
			<th></th>
			<th></th>
			<th></th>

			<th>DTCC Id</th>
			<th>TimeStamp</th>
			<th>UND</th>
			<th>ACC</th>
			<th>UND Notional</th>
			<th>ACC Notional</th>
			<th>USD Equiv Notional</th>
			<th>Strike</th>
			<th>Sub Type</th>
			<th>Expiry</th>
			<th>PAY</th>
			<th>Prem</th>
			<th>Trade Type</th>
			<th>Spot Ref</th>
		</tr>
	</thead>

	<tbody>
		<% @trades.each do |trade| %>
		<tr>
			<td><%= link_to 'Show', trade %></td>
			<td><%= link_to 'Edit', edit_trade_path(trade) %></td>
			<td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>

			<td><%= trade.dtcc_id  %> </td>
			<% ts = Time.parse(trade.time_stamp.to_s) if trade.time_stamp %>
			<td><%= ts.strftime( '%Y %b %d %H:%M:%S' ) if trade.time_stamp  %> </td>
			<td><%= trade.und %> </td>
			<td><%= trade.acc %> </td>
			<td><%= number_with_precision(trade.und_not, :precision => 0, :delimiter => ',') %> </td>
			<td><%= number_with_precision(trade.acc_not, :precision => 0, :delimiter => ',')  %> </td>
			<td><%= number_with_precision(trade.m_usd_equiv_not, :precision => 0, :delimiter => ',')  %> </td>
			<td><%= trade.strike %> </td>
			<td><%= trade.type %> </td>
			<% ts = Time.parse(trade.expiry.to_s) if trade.expiry %>
			<td><%= ts.strftime( '%d %b %Y' ) if trade.expiry  %> </td>
			<td><%= trade.prem_ccy %> </td>
			<td><%= number_with_precision(trade.prem, :precision => 0, :delimiter => ',') %> </td>			
			<td><%= trade.taxonomy %> </td>
			<td><%= trade.m_spot_ref %> </td>
		</tr>
		<% end %>
	</tbody>
</table>

<br />



<%= link_to 'New Trade', new_trade_path %>

app/views/trades/new.html.erb
<h1>New trade</h1>

<%= render 'form' %>

<%= link_to 'Back', trades_path %>

app/views/trades/pair.html.erb
<h1>Trade list by pair summary (100 limit)</h1>

<h2> Most recent <%=params[:pair]%> trades > $25mio equiv </h2>
<table id ='trade_table'>
	<thead>
		<tr>
			<th></th>
			<th></th>
			<th></th>

			<th>DTCC Id</th>
			<th>TimeStamp</th>
			<th>UND</th>
			<th>ACC</th>
			<th>UND Notional</th>
			<th>ACC Notional</th>
			<th>USD Equiv Notional</th>
			<th>Strike</th>
			<th>Sub Type</th>
			<th>Expiry</th>
			<th>PAY</th>
			<th>Prem</th>
			<th>Trade Type</th>
			<th>Spot Ref</th>
		</tr>
	</thead>

	<tbody>
		<% @trades.each do |trade| %>
		<tr>
			<td><%= link_to 'Show', trade %></td>
			<td><%= link_to 'Edit', edit_trade_path(trade) %></td>
			<td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>

			<td><%= trade.dtcc_id  %> </td>
			<% ts = Time.parse(trade.time_stamp["d"]+" "+trade.time_stamp["t"]) if trade.time_stamp %>
			<td><%= ts.strftime( '%Y %b %d %H:%M:%S' ) if trade.time_stamp  %> </td>
			<td><%= trade.und %> </td>
			<td><%= trade.acc %> </td>
			<td><%= number_with_precision(trade.und_not, :precision => 0, :delimiter => ',') %> </td>
			<td><%= number_with_precision(trade.acc_not, :precision => 0, :delimiter => ',')  %> </td>
			<td><%= number_with_precision(trade.m_usd_equiv_not, :precision => 0, :delimiter => ',')  %> </td>
			<td><%= trade.strike %> </td>
			<td><%= trade.type %> </td>
			<% ts = Time.parse(trade.expiry.to_s) if trade.expiry %>
			<td><%= ts.strftime( '%d %b %Y' ) if trade.expiry  %> </td>
			<td><%= trade.prem_ccy %> </td>
			<td><%= number_with_precision(trade.prem, :precision => 0, :delimiter => ',') %> </td>			
			<td><%= trade.taxonomy %> </td>
			<td><%= trade.m_spot_ref %> </td>
		</tr>
		<% end %>
	</tbody>
</table>
<br />


<%= link_to 'New Trade', new_trade_path %>

app/views/trades/range.html.erb
<h1>Trade list summary (100 limit)</h1>


<p>
	<%= date_select "report", "start_date", :default => -1.days.from_now %>
	to <%= date_select "report", "end_date", :default => 0.days.from_now %>
</p>

<h2> Latest (<%=@trades.count%>/100) all trades </h2>
<table id ='trade_table'>
	<thead>
		<tr>
			<th></th>
			<th></th>
			<th></th>

			<th>DTCC Id</th>
			<th>TimeStamp</th>
			<th>UND</th>
			<th>ACC</th>
			<th>UND Notional</th>
			<th>ACC Notional</th>
			<th>Strike</th>
			<th>Sub Type</th>
			<th>Expiry</th>
			<th>PAY</th>
			<th>Prem</th>
			<th>Trade Type</th>
		</tr>
	</thead>

	<tbody>
		<% @trades.each do |trade| %>
		<tr>
			<td><%= link_to 'Show', trade %></td>
			<td><%= link_to 'Edit', edit_trade_path(trade) %></td>
			<td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>

			<td><%= trade.dtcc_id  %> </td>
			<td><%= Time.parse(trade.time_stamp).strftime( '%Y %b %d %H:%M:%S' ) if trade.time_stamp  %> </td>
			<td><%= trade.und %> </td>
			<td><%= trade.acc %> </td>
			<td><%= number_with_precision(trade.und_not, :precision => 0, :delimiter => ',') %> </td>
			<td><%= number_with_precision(trade.acc_not, :precision => 0, :delimiter => ',')  %> </td>
			<td><%= trade.strike %> </td>
			<td><%= trade.type %> </td>
			<td><%= trade.expiry.strftime( '%d %b %y' ) if trade.expiry %> </td>
			<td><%= trade.prem_ccy %> </td>
			<td><%= number_with_precision(trade.prem, :precision => 0, :delimiter => ',') %> </td>			
			<td><%= trade.taxonomy %> </td>
		</tr>
		<% end %>
	</tbody>
</table>
<br />

<h2> Latest (<%=@opt_trades.count%>/100) all trades </h2>
<table id ='trade_table'>
	<thead>
		<tr>
			<th></th>
			<th></th>
			<th></th>

			<th>DTCC Id</th>
			<th>TimeStamp</th>
			<th>UND</th>
			<th>ACC</th>
			<th>UND Notional</th>
			<th>ACC Notional</th>
			<th>Strike</th>
			<th>Sub Type</th>
			<th>Expiry</th>
			<th>PAY</th>
			<th>Prem</th>
			<th>Trade Type</th>
		</tr>
	</thead>

	<tbody>
		<% @opt_trades.each do |trade| %>
		<tr>
			<td><%= link_to 'Show', trade %></td>
			<td><%= link_to 'Edit', edit_trade_path(trade) %></td>
			<td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>

			<td><%= trade.dtcc_id  %> </td>
			<td><%= Time.parse(trade.time_stamp).strftime( '%Y %b %d %H:%M:%S' ) if trade.time_stamp  %> </td>
			<td><%= trade.und %> </td>
			<td><%= trade.acc %> </td>
			<td><%= number_with_precision(trade.und_not, :precision => 0, :delimiter => ',') %> </td>
			<td><%= number_with_precision(trade.acc_not, :precision => 0, :delimiter => ',')  %> </td>
			<td><%= trade.strike %> </td>
			<td><%= trade.type %> </td>
			<td><%= trade.expiry.strftime( '%d %b %y' ) if trade.expiry %> </td>
			<td><%= trade.prem_ccy %> </td>
			<td><%= number_with_precision(trade.prem, :precision => 0, :delimiter => ',') %> </td>			
			<td><%= trade.taxonomy %> </td>
		</tr>
		<% end %>
	</tbody>
</table>


<%= link_to 'New Trade', new_trade_path %>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<h2> Trade[<%= @trade.dtcc_id  %>]</h2>

<ul>
	<% @trade.attributes.each_pair do |name, value| %>
	<li> <%= name %> = <%= value %> </li>
	<% end %>
</ul>

<%= link_to 'Edit', edit_trade_path(@trade) %> |
<%= link_to 'Back', trades_path %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>